### ISSUE TITLE
Respawning At The Same Place

### ISSUE THREAD

**Issue by willpsdk** [Flamtky/fivem-respawn-nearby#4]
Hey Im not very good at this kind of stuff so could I please have some help? I keep respawning at the same place even if i go to the other side of the map. I have attached a video of the problem.

https://youtu.be/8pnFaSj3cYk

Thanks!

**Comment by willpsdk** [comment]
It spawns me in the same place every time!

**Comment by Flamtky** [comment]
Hey thanks for reporting this! It looks like we have the same problem as in #3, so I'll close the issue here so we can merge the discussion into one issue. I'm currently a bit busy with other projects, but it would be great if you could test the [current dev branch](https://github.com/Flamtky/fivem-respawn-nearby/archive/refs/heads/dev.zip) and then post me the console output after the error (respawning) happened.

**Comment by willpsdk** [comment]
Hey Do I have to put in the command for it to work? I dont really get what and where the goes if you could reply and tell me the command and where to put it I would really be grateful!

Thanks

**Comment by Flamtky** [comment]
What command? But you can open the FiveM console with `F8`
