### ISSUE TITLE
I respawn under the  map

### ISSUE THREAD

**Issue by Sn0mTV** [Flamtky/fivem-respawn-nearby#6]
I installed everything where it was needed but when I spawn I spawn in the same place and when I respawn I respawn in the same place as where I spawned the first time even if I die on the other side of the map + when I respawn I respawn under the map

**Comment by Flamtky** [comment]
@Sn0mTV 
Okay... Is the problem still present? since you closed the issue. If so, I would need more information, e.g. the output from your console (can be opened ingame via F8). Additionally, I don't quite understand the problem, do you always spawn under the map? Or do you respawn at the same place where you died? Or both? Some more context would be nice.

**Comment by briansimple** [comment]
I can rewrite it so that when you join the server you always end up at 0 0 1.
Can we deactivate that for joining?
(Translate with DeepL)

**Comment by Flamtky** [comment]
Hi @briansimple,
thanks for your comment. I'm having some difficulty understanding your point/problem. Could you help me by possibly providing me with the following data:
1. Console output: open the console in game (F8) and share the output, with DEBUG_PRINTS enabled.
2. problem description: What exactly happens when you respawn? Does it always happen or only sometimes? Or is it during the initial respawn?

**Comment by briansimple** [comment]
DEUTSCH:
ich habe keine infos aus der console.

mein problem ist das ich immer wenn ich auf den server joine immer bei 0 0 1 lande. 
Es wird anscheinend kein Unterschied gemacht, ob ich auf den Server joine oder nach dem Tod respawne. da das script aber keinen letzten tod feststellen kann will es mich bei 0 0 70 spawnen, was nicht funktioniert.
Das respwanen nach dem tod funktioniert einwandfrei.

ENGLISH:
I don't have any information from the console 

My problem is that whenever I join the server I always end up at 0 0 1. 
There doesn't seem to be any difference whether I join the server or respawn after death. But since the script can't determine a final death, it wants to spawn me at 0 0 70, which doesn't work.
Respawning after death works perfectly.
(Translate with DeepL)

**Comment by briansimple** [comment]
mit der neuen version ist es behoben - danke
